source 'https://github.com/jiaojiaozhe/XAbstractionLibrary-Specs'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'ComponentModuleC_Example' do
  pod 'ComponentModuleC', :path => '../'

  target 'ComponentModuleC_Tests' do
    inherit! :search_paths

    
  end
end
